# Generated by Django 3.1.14 on 2023-12-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20231217_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='company_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
