# Generated by Django 3.1.14 on 2023-12-17 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_joblisting_company_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjob',
            name='job_listing',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jobs.joblisting'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='company_email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
