# Generated by Django 3.1.14 on 2023-12-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20231217_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='company_email',
            field=models.EmailField(blank=True, default='edigitalnetwork842@gmail.com', max_length=254, null=True),
        ),
    ]
