# Generated by Django 3.1.14 on 2023-12-21 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20231218_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyjob',
            name='user_profile',
        ),
    ]
