# Generated by Django 4.0.8 on 2024-01-07 22:33

from django.db import migrations, models
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_alter_joblisting_company_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, validators=[jobs.models.validate_bio_word_count]),
        ),
    ]
