# Generated by Django 4.0.8 on 2024-01-14 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_alter_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
